services:
  backend:
    env_file: .env
    environment:
      AZURE_PASSWORD: ${AZURE_PASSWORD}
      DJANGO_SECRET: ${DJANGO_SECRET}
    image: campusmarket.azurecr.io/campusmarket-backend
    build: ./backend
    ports:
      - "8080:8080"
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"
  frontend:
    image: campusmarket.azurecr.io/campusmarket-frontend
    build: ./frontend
    ports:
      - "443:443"
