services:
  backend:
    image: campusmarket.azurecr.io/campusmarket-backend
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      AZURE_PASSWORD: ${AZURE_PASSWORD}
      DJANGO_SECRET: ${DJANGO_SECRET}
  frontend:
    image: campusmarket.azurecr.io/campusmarket-frontend
    build: ./frontend
    ports:
      - "3000:3000"
