services:
  backend:
    image: campusmarket3.azurecr.io/campusmarket-backend
    build: ./backend
    networks:
      - mynetwork
    environment:
      AZURE_PASSWORD: ${AZURE_PASSWORD}
      DJANGO_SECRET: ${DJANGO_SECRET}
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
  frontend:
    image: campusmarket3.azurecr.io/campusmarket-frontend
    build: ./frontend
    networks:
      - mynetwork
    ports:
      - "3000:3000"
networks:
  mynetwork:
    driver: bridge
